apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcharr-prod-pvc
  namespace: dispatcharr
  labels:
    app: dispatcharr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi