apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-prod-media-config
  namespace: media
data:
  qBittorrent.conf: |
    [Application]
    FileLogger\Age=1
    FileLogger\AgeType=1
    FileLogger\Backup=true
    FileLogger\DeleteOld=true
    FileLogger\Enabled=true
    FileLogger\MaxSizeBytes=66560
    FileLogger\Path=/config/qBittorrent/logs
    MemoryWorkingSetLimit=2048

    [AutoRun]
    enabled=false
    program=

    [BitTorrent]
    MergeTrackersEnabled=true
    Session\AddExtensionToIncompleteFiles=true
    Session\AddTorrentStopped=false
    Session\DefaultSavePath=/complete/
    Session\DisableAutoTMMByDefault=false
    Session\ExcludedFileNames=
    Session\IncludeOverheadInLimits=true
    Session\MaxActiveDownloads=6
    Session\MaxActiveTorrents=10
    Session\MaxActiveUploads=4
    Session\MaxConnections=5000
    Session\MaxConnectionsPerTorrent=1000
    Session\MaxUploads=200
    Session\MaxUploadsPerTorrent=40
    Session\PerformanceWarning=true
    Session\Port=6881
    Session\Preallocation=true
    Session\QueueingSystemEnabled=true
    Session\SSL\Port=43058
    Session\ShareLimitAction=Stop
    Session\TempPath=/downloads/incomplete/
    Session\TempPathEnabled=true

    [Core]
    AutoDeleteAddedTorrentFile=IfAdded

    [LegalNotice]
    Accepted=true

    [Meta]
    MigrationVersion=8

    [Network]
    PortForwardingEnabled=false
    Proxy\HostnameLookupEnabled=false
    Proxy\Profiles\BitTorrent=true
    Proxy\Profiles\Misc=true
    Proxy\Profiles\RSS=true

    [Preferences]
    Connection\PortRangeMin=6881
    Connection\UPnP=false
    Downloads\SavePath=/complete/
    Downloads\TempPath=/downloads/incomplete/
    General\Locale=en
    General\StatusbarExternalIPDisplayed=true
    MailNotification\req_auth=true
    WebUI\Address=*
    WebUI\AuthSubnetWhitelist=10.244.0.0/16
    WebUI\AuthSubnetWhitelistEnabled=true
    WebUI\ServerDomains=*

    [RSS]
    AutoDownloader\DownloadRepacks=true
    AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
