apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-arpa-tls
  namespace: authentik
spec:
  secretName: home-arpa-tls
  issuerRef:
    kind: ClusterIssuer
    name: home-ca-issuer
  commonName: home.arpa
  dnsNames:
    - authentik.home.arpa
    - ldap.home.arpa
    - ak-outpost-home-ldap-outpost.authentik.svc.cluster.local
    - sonarr.home.arpa
    - radarr.home.arpa
    - prowlarr.home.arpa
    - bazarr.home.arpa
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
