apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: secret-key
  namespace: authentik
spec:
  length: 24
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: "30s"
  target:
    name: authentik-secrets
  dataFrom:
  - sourceRef:
      generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: secret-key