apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: secret-key
  namespace: authentik
spec:
  length: 64
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: "0"
  target:
    name: authentik-secrets
  data:
    - secretKey: secret-key
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: secret-key