apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: authentik-secrets
spec:
  length: 64
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
  secretKeys:
    - secret-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
spec:
  refreshPolicy: OnChange
  target:
    name: authentik-secrets
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: authentik-secrets
