apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr-prod-media-ingress
  namespace: media-control
  annotations: 
    cert-manager.io/cluster-issuer: home-ca-issuer
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - radarr.home.arpa
    secretName: media-prod-tls-internal
  rules:
  - host: "radarr.home.arpa"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: radarr-prod-media-svc
            port:
              number: 7878