apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr-prod-media-ingress
  namespace: media-control
spec:
  ingressClassName: nginx
  rules:
  - host: "bazarr.home.arpa"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: bazarr-prod-media-svc
            port:
              number: 6767