apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-arpa-tls
  namespace: media
spec:
  secretName: home-arpa-tls
  issuerRef:
    kind: ClusterIssuer
    name: home-ca-issuer
  commonName: home.arpa
  dnsNames:
    - jellyfin.home.arpa
    - dispatcharr.home.arpa
    - qbittorrent-0.home.arpa
    - qbittorrent-1.home.arpa
    - qbittorrent-2.home.arpa
    - seerr.home.arpa
  privateKey:
    algorithm: RSA
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
