apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bazarr
  namespace: default
spec:
  interval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./apps/media/bazarr
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radarr
  namespace: default
spec:
  interval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./apps/media/radarr
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./apps/media/sonarr
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
  namespace: default
spec:
  interval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./apps/media/seerr
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dispatcharr
  namespace: default
spec:
  interval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./apps/media/dispatcharr
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./apps/media/jellyfin
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prowlarr
  namespace: default
spec:
  interval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./apps/media/prowlarr
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: default
spec:
  interval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./apps/media/qbittorrent
  prune: false
