apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-prod-media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
