apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media
  namespace: default
spec:
  interval: 30s
  timeout: 5m
  dependsOn:
    - name: configs
  sourceRef:
    kind: ExternalArtifact
    name: apps
  path: ./production/media
  prune: false
