apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: default
spec:
  interval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./infrastructure/metallb
  prune: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: default
spec:
  interval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./infrastructure/longhorn
  prune: false