apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-media-drive
  namespace: longhorn-system
  labels:
    usage: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-rwx-optimized
  resources:
    requests:
      storage: 20Gi