apiVersion: v1
kind: Service
metadata:
  labels:
    longhorn.io/component: share-manager
    longhorn.io/managed-by: longhorn-manager
    longhorn.io/share-manager: pvc-9dfb4971-ae06-4a24-af63-d087714c00ee
    longhorn.io/share-manager-image: smi-e2d9dcfd
  name: shared-media
  namespace: longhorn-system
spec:
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
      targetPort: 2049
  type: LoadBalancer
  loadBalancerIP: 192.168.40.6
  selector:
    longhorn.io/component: share-manager
    longhorn.io/managed-by: longhorn-manager
    longhorn.io/share-manager: pvc-9dfb4971-ae06-4a24-af63-d087714c00ee
    longhorn.io/share-manager-image: smi-e2d9dcfd
status:
  loadBalancer: {}
