apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-server-provisioner
  namespace: default
spec:
  install:
    createNamespace: true
  targetNamespace: nfs-server-provisioner
  interval: 10m
  chart:
    spec:
      chart: nfs-server-provisioner
      sourceRef:
        kind: HelmRepository
        name: nfs-ganesha-server-and-external-provisioner
        namespace: default
      interval: 10m
  values:
    nodeSelector:
      kubernetes.io/hostname: talos-uh1-bo3

    persistence:
      enabled: true
      storageClass: "-"
      size: 1000Gi
