apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dispatcharr
  namespace: flux-system
spec:
  interval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./apps/media/playback/dispatcharr
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  interval: 30s
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: homelab-github-flux-sync
    namespace: flux-system
  path: ./apps/media/playback/jellyfin
  prune: true
