apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: home-arpa-tls
spec:
  externalSecretName: home-arpa-tls
  namespaceSelectors:
    - matchLabels: {}
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: ca-store
    target:
      name: home-arpa-tls
    data:
      - secretKey: tls.crt
        remoteRef:
          key: home-arpa-tls
          property: tls.crt
      - secretKey: tls.key
        remoteRef:
          key: home-arpa-tls
          property: tls.key
      - secretKey: ca.crt
        remoteRef:
          key: home-arpa-tls
          property: ca.crt