apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: home-root-ca
spec:
  externalSecretName: home-root-ca
  namespaceSelectors:
    - matchLabels: {}
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: ca-store
    target:
      name: home-root-ca
    data:
      - secretKey: ca.crt
        remoteRef:
          key: home-root-ca
          property: ca.crt
