apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-arpa-tls
  namespace: external-secrets
spec:
  dnsNames:
    - "*.home.arpa"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: home-ca-issuer
  secretName: home-arpa-tls
  usages:
    - digital signature
    - key encipherment
