apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName: nfs
  resources:
    requests:
      storage: 800Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
