apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-media-share-nfs-server-provisioner-0
spec:
  
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/mnt/media-data
  claimRef:
    namespace: media-share
    name: data-media-share-nfs-server-provisioner-0