apiVersion: v1
kind: Service
metadata:
  name: nfs
  namespace: media-share
spec:
  clusterIP: 10.106.110.148
  clusterIPs:
  - 10.106.110.148
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: nfs
    port: 2049
    protocol: TCP
    targetPort: nfs
  selector:
    app: nfs-server-provisioner
    release: media-share-nfs-server-provisioner
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
