apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfd
  namespace: default
spec:
  suspend: false
  install:
    createNamespace: true
  targetNamespace: nfd
  interval: 10m
  chart:
    spec:
      chart: node-feature-discovery
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: default
      interval: 10m
      version: 0.19.0
  values:
    worker:
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
