apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-config
spec:
  refreshPolicy: OnChange
  target:
    template:
      engineVersion: v2
      data:
        config.xml: |
          <Config>
            <BindAddress>*</BindAddress>
            <Port>7878</Port>
            <SslPort>9898</SslPort>
            <EnableSsl>False</EnableSsl>
            <LaunchBrowser>True</LaunchBrowser>
            <ApiKey>{{index . `api-key`}}</ApiKey>
            <AuthenticationMethod>External</AuthenticationMethod>
            <AuthenticationRequired>Enabled</AuthenticationRequired>
            <Branch>master</Branch>
            <LogLevel>debug</LogLevel>
            <SslCertPath></SslCertPath>
            <SslCertPassword></SslCertPassword>
            <UrlBase></UrlBase>
            <InstanceName>Radarr</InstanceName>
          </Config>
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: radarr-media-apikey
