apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-cluster-issuer
spec:
  acme:
    email: charlie@cbxon.co.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-clusterissuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-key
            key: apiKey
