apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      initContainers:
        - name: build-ca-bundle
          securityContext:
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
        - name: copy-config
          securityContext:
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
