apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-share
  namespace: media-playback
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 950Gi