apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: seerr-oidc-secrets
  namespace: media-control
spec:
  length: 42
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true
  secretKeys:
    - client-id
    - client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-oidc-config
  namespace: media-control
spec:
  target:
    name: seerr-oidc-config
    template:
      engineVersion: v2
      data:
        config.json: |
          {
            "main": {
              "oidcLogin": true
            },
            "oidc": {
              "providers": [
                {
                  "slug": "authentik",
                  "name": "authentik",
                  "issuerUrl": "https://authentik.company/application/o/<application_slug>/",
                  "clientId": "{{ index . \"client-id\" }}",
                  "clientSecret": "{{ index . \"client-secret\" }}",
                  "logo": "https://authentik.company/static/dist/assets/icons/icon.svg",
                  "newUserLogin": true
                }
              ]
            }
          }
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: seerr-oidc-secrets