apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qui-deployment
  name: qui-deployment
  namespace: media
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qui-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: qui-deployment
    spec:
      # securityContext:
      #   fsGroup: 10000
      #   runAsGroup: 10000
      #   runAsNonRoot: true
      #   runAsUser: 10000
      #   seccompProfile:
      #     type: RuntimeDefault
      #   readOnlyRootFilesystem: true
      # automountServiceAccountToken: false
      containers:
      - image: ghcr.io/autobrr/qui:latest
        name: qui
        resources: {}
        ports:
          - containerPort: 7476
            name: http
            protocol: TCP
        env:
          - name: QUI__SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: qui-session-secret
                key: session-secret
          - name: QUI__DATABASE_ENGINE
            value: postgres
          - name: QUI__DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: qbittorrent-prod-pg-app
                key: host
          - name: QUI__DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: qbittorrent-prod-pg-app
                key: username
          - name: QUI__DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: qbittorrent-prod-pg-app
                key: password
          - name: QUI__DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: qbittorrent-prod-pg-app
                key: dbname
status: {}
