apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: qui-session-secret
spec:
  length: 33
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - sessionSecret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-session-secret
spec:
  refreshPolicy: OnChange
  target:
    template:
      data:
        SESSION_SECRET: '{{ index . "sessionSecret" }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: qui-session-secret
