apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: media-apikey
spec:
  length: 33
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - api-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-config
spec:
  refreshPolicy: OnChange
  target:
    template:
      data:
        config.xml:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: media-apikey
